# Generated by Django 5.2.8 on 2025-11-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_equipo_partidocompetitivo_invitacionequipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones de la reserva', null=True),
        ),
        migrations.CreateModel(
            name='HorarioCancha',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='0=Lunes, 6=Domingo')),
                ('hora_inicio', models.TimeField(help_text='Hora de apertura')),
                ('hora_fin', models.TimeField(help_text='Hora de cierre')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='eventos.cancha')),
            ],
            options={
                'verbose_name': 'Horario de Cancha',
                'verbose_name_plural': 'Horarios de Canchas',
                'db_table': 'horarios_cancha',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('id_cancha', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
