# Generated by Django 5.2.8 on 2025-11-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0003_usuario_biografia_usuario_fecha_nacimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('color_primario', models.CharField(default='#007bff', help_text='Color en formato hexadecimal', max_length=7)),
                ('color_secundario', models.CharField(default='#ffffff', help_text='Color en formato hexadecimal', max_length=7)),
                ('id_anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipos',
            },
        ),
        migrations.CreateModel(
            name='PartidoCompetitivo',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.CharField(help_text='Nombre del lugar si no hay cancha registrada', max_length=200)),
                ('fecha_hora', models.DateTimeField()),
                ('goles_local', models.IntegerField(default=0)),
                ('goles_visitante', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cancha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.cancha')),
                ('id_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_competitivos_creados', to=settings.AUTH_USER_MODEL)),
                ('id_equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='competitiva.equipo')),
                ('id_equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='competitiva.equipo')),
                ('id_localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventos.localidad')),
            ],
            options={
                'verbose_name': 'Partido Competitivo',
                'verbose_name_plural': 'Partidos Competitivos',
                'db_table': 'partidos_competitivos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='InvitacionEquipo',
            fields=[
                ('id_invitacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='competitiva.equipo')),
                ('id_invitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_equipo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitación a Equipo',
                'verbose_name_plural': 'Invitaciones a Equipos',
                'db_table': 'invitaciones_equipo',
                'ordering': ['-fecha_invitacion'],
                'unique_together': {('id_equipo', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id_miembro', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('anfitrion', 'Anfitrión'), ('capitan', 'Capitán'), ('jugador', 'Jugador')], default='jugador', max_length=20)),
                ('numero_camiseta', models.IntegerField(blank=True, null=True)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='competitiva.equipo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_miembro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Equipo',
                'verbose_name_plural': 'Miembros de Equipo',
                'db_table': 'miembros_equipo',
                'unique_together': {('id_equipo', 'id_usuario')},
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('goles', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('tarjetas_amarillas', models.IntegerField(default=0)),
                ('tarjetas_rojas', models.IntegerField(default=0)),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitiva.equipo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_competitivas', to=settings.AUTH_USER_MODEL)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='competitiva.partidocompetitivo')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
                'db_table': 'estadisticas_jugador',
                'unique_together': {('id_partido', 'id_usuario')},
            },
        ),
    ]
